### ISSUE TITLE
Research google maps API.

### ISSUE THREAD

**Issue by Mattdack** [Mattdack/hiking-app#7]

**Comment by shreyamishra9618** [comment]
How to generate a Google Maps API key
 The first thing you’ll need to do is create a Google Cloud Platform account if you don’t have one already.

 Here are the five simple steps to generate your Google Maps API key:

 Log in to the Google Cloud Platform Console
 Select an existing project or create a new one to add an API key to
 Navigate to the APIs & Services > Credentials page
 On the Credentials page, click Create credentials > API key and follow the prompts
 Click close and confirm your key has been created

**Comment by LiyuanSilviaZhao** [comment]
https://developers.google.com/maps/apis-by-platform 

Web APIs
[Maps Embed API](https://developers.google.com/maps/documentation/embed/guide). Add a Google Map to your site without code or quota limits.

[Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/tutorial). Customize maps with your own content and imagery.

[Places Library, Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/places). Up-to-date information about millions of locations.

[Maps Static API](https://developers.google.com/maps/documentation/maps-static). Simple, embeddable map image with minimal code.

[Street View Static API](https://developers.google.com/maps/documentation/streetview). Real-world imagery and panoramas.

Web Service APIs
[Directions API](https://developers.google.com/maps/documentation/directions). Directions between multiple locations.

[Distance Matrix API](https://developers.google.com/maps/documentation/distance-matrix). Travel time and distance for multiple destinations.

[Elevation API](https://developers.google.com/maps/documentation/elevation). Elevation data for any point in the world.

[Geocoding API](https://developers.google.com/maps/documentation/geocoding). Convert between addresses and geographic coordinates.

[Geolocation API](https://developers.google.com/maps/documentation/geolocation). Location data from cell towers and WiFi nodes.

[Places API](https://developers.google.com/maps/documentation/places/web-service). Up-to-date information about millions of locations.

[Roads API](https://developers.google.com/maps/documentation/roads). Snap-to-road functionality to accurately trace GPS breadcrumbs.

[Time Zone API](https://developers.google.com/maps/documentation/timezone). Time zone data for anywhere in the world.
